"""empty message

Revision ID: 721dfa531caf
Revises: a064715f2237
Create Date: 2024-10-22 18:33:58.648469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721dfa531caf'
down_revision = 'a064715f2237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
