"""empty message

Revision ID: 8708becdb82a
Revises: d08d37154f40
Create Date: 2024-10-24 11:44:36.491958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8708becdb82a'
down_revision = 'd08d37154f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('payment_details')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
