"""empty message

Revision ID: 95dec7e4fe94
Revises: 21bf64c4093c
Create Date: 2024-10-21 16:09:03.010407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dec7e4fe94'
down_revision = '21bf64c4093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_addresses', schema=None) as batch_op:
        batch_op.alter_column('line1',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('doc_addresses', schema=None) as batch_op:
        batch_op.alter_column('line1',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
