"""Add appointment model

Revision ID: db8f607cf212
Revises: 6e63311155a8
Create Date: 2024-10-23 23:40:58.190673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8f607cf212'
down_revision = '6e63311155a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('docId', sa.Integer(), nullable=False),
    sa.Column('slotDate', sa.String(), nullable=False),
    sa.Column('slotTime', sa.String(), nullable=False),
    sa.Column('userData', sa.JSON(), nullable=False),
    sa.Column('docData', sa.JSON(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Numeric(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=False),
    sa.Column('isCompleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
